// Copyright 2017-2026 @pezkuwi/apps-config authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @pezkuwi/apps-config

import type { OverrideBundleType } from '@pezkuwi/types/types';

/* eslint-disable @stylistic/quotes */
/* eslint-disable @stylistic/quote-props */

export const typesBundle = {
  "chain": {},
  "spec": {}
} as unknown as OverrideBundleType;
