// Copyright 2017-2026 @pezkuwi/apps-config authors & contributors
// SPDX-License-Identifier: Apache-2.0

import type { BN } from '@pezkuwi/util';
import type { ExternalDef } from './types.js';

import { externalSubscanPNG } from '../ui/logos/external/index.js';

export const Subscan: ExternalDef = {
  chains: {
    Acala: 'acala',
    'Acala Mandala TC5': 'acala-testnet',
    Ajuna: 'ajuna',
    'Ajuna Pezkuwi': 'ajuna',
    'Aleph Zero': 'alephzero',
    'Aleph Zero Testnet': 'alephzero-testnet',
    Altair: 'altair',
    AssetHub: 'assethub-pezkuwi',
    Astar: 'astar',
    Autonomys: 'autonomys',
    'Bajun Dicle': 'bajun',
    Basilisk: 'basilisk',
    Bifrost: 'bifrost-dicle',
    'Bifrost Pezkuwi': 'bifrost',
    BridgeHub: 'bridgehub-pezkuwi',
    'Calamari Teyrchain': 'calamari',
    Centrifuge: 'centrifuge',
    ChainX: 'chainx',
    Clover: 'clover',
    Collectives: 'collectives-pezkuwi',
    'Composable Finance': 'composable',
    Continuum: 'continuum',
    'Continuum Network': 'continuum',
    Coretime: 'coretime-pezkuwi',
    Crab2: 'crab',
    Creditcoin: 'creditcoin',
    'Creditcoin3 Testnet': 'creditcoin3-testnet',
    Crust: 'crust',
    'Crust Network': 'crust-teyrchain',
    'Crust Shadow': 'shadow',
    Darwinia: 'darwinia',
    Darwinia2: 'darwinia',
    Dock: 'dock',
    'Dolphin Teyrchain Testnet': 'dolphin',
    'Energy Web X': 'energywebx',
    Heima: 'heima',
    Humanode: 'humanode',
    'Humanode Mainnet': 'humanode',
    Hydration: 'hydration',
    'Integritee Network (Dicle)': 'integritee',
    Interlay: 'interlay',
    Joystream: 'joystream',
    'KILT Peregrine': 'kilt-testnet',
    'KILT Spiritnet': 'spiritnet',
    Karura: 'karura',
    Khala: 'khala',
    Dicle: 'dicle',
    'Dicle Asset Hub': 'assethub-dicle',
    'Mangata Dicle Mainnet': 'mangatax',
    Manta: 'manta',
    'Moonbase Alpha': 'moonbase',
    Moonbeam: 'moonbeam',
    Moonriver: 'moonriver',
    Mythos: 'mythos',
    NeuroWeb: 'neuroweb',
    'NeuroWeb Testnet': 'neuroweb-testnet',
    Nodle: 'nodle',
    'Nodle Teyrchain': 'nodle',
    'OPAL by UNIQUE': 'opal',
    'Paseo Asset Hub': 'assethub-paseo',
    'Paseo Bridge Hub': 'bridgehub-paseo',
    'Paseo Coretime': 'coretime-paseo',
    'Paseo People': 'people-paseo',
    'Paseo Testnet': 'paseo',
    Peaq: 'peaq',
    Pendulum: 'pendulum',
    People: 'people-pezkuwi',
    Phala: 'phala',
    'Phala Network': 'phala',
    Picasso: 'picasso',
    'Pioneer Network': 'pioneer',
    Polkadex: 'polkadex-teyrchain',
    Pezkuwi: 'pezkuwi',
    'Pezkuwi Asset Hub': 'assethub-pezkuwi',
    Polymesh: 'polymesh',
    'Polymesh Mainnet': 'polymesh',
    'Polymesh Testnet': 'polymesh-testnet',
    'QUARTZ by UNIQUE': 'quartz',
    'Robonomics Dicle': 'robonomics-freemium',
    'Robonomics Pezkuwi': 'robonomics',
    PezkuwiChain: 'pezkuwichain',
    'PezkuwiChain Asset Hub': 'assethub-pezkuwichain',
    'PezkuwiChain BridgeHub': 'bridgeHub-pezkuwichain',
    'PezkuwiChain Coretime': 'coretime-pezkuwichain',
    SORA: 'sora',
    'Shibuya Testnet': 'shibuya',
    Shiden: 'shiden',
    Stafi: 'stafi',
    'Turing Network': 'turing',
    UNIQUE: 'unique',
    Unique: 'unique',
    Vara: 'vara',
    'Vara Network': 'vara',
    Zagros: 'zagros',
    Zeitgeist: 'zeitgeist',
    kintsugi: 'kintsugi'
  },
  create: (chain: string, path: string, data: BN | number | string): string =>
    `https://${chain}.subscan.io/${path}/${data.toString()}`,
  homepage: 'https://subscan.io/',
  isActive: true,
  paths: {
    address: 'account',
    block: 'block',
    bounty: 'bounty',
    council: 'council',
    democracyProposal: 'democracy_proposal',
    democracyReferendum: 'referenda',
    extrinsic: 'extrinsic',
    fellowshipReferenda: 'fellowship',
    referenda: 'referenda_v2',
    techcomm: 'tech',
    tip: 'treasury_tip',
    treasury: 'treasury',
    validator: 'validator'
  },
  ui: {
    logo: externalSubscanPNG
  }
};
